import * as FileSystem from 'expo-file-system/legacy';

export interface ExtractedFrame {
  frameIndex: number;
  timestampMs: number;
  uri: string;
}

const FPS = 30;
// 10 seconds covers real-time serves (~2s) up to ~8x slow-motion (~16s).
// Synthetic frames spread evenly across this window so phase detection
// sees the full serve arc regardless of recording speed.
const ESTIMATED_DURATION_MS = 10000;

// Generates synthetic frame metadata — no native modules required.
// The video URI is passed through so SkeletonScrubber can play the real video;
// pose keypoints are generated by poseDetector (mock or real) separately.
export async function extractFrames(
  videoUri: string,
  onProgress?: (progress: number) => void
): Promise<ExtractedFrame[]> {
  const totalFrames = Math.round((ESTIMATED_DURATION_MS / 1000) * FPS);
  const frames: ExtractedFrame[] = Array.from({ length: totalFrames }, (_, i) => ({
    frameIndex: i,
    timestampMs: Math.round((i / FPS) * 1000),
    uri: videoUri,
  }));
  onProgress?.(100);
  return frames;
}

export async function extractThumbnail(_videoUri: string): Promise<string | null> {
  return null;
}

export async function clearFrameCache(): Promise<void> {
  const dir = `${FileSystem.cacheDirectory ?? ''}contactpoint_frames/`;
  const info = await FileSystem.getInfoAsync(dir);
  if (info.exists) {
    await FileSystem.deleteAsync(dir, { idempotent: true });
  }
}
